"""
narrative.py
The report body, written to the individual word allocation scaled to a 2,500-word total
(125 / 250 / 375 / 500 / 375 / 375 / 200 / 175 / 125). Appendices and references sit outside the count.
All quantities are injected from the real run artefacts at build time.
"""


def build_sections(TESTS, PASSED, FAILED, ENDPOINTS, EXCHANGES, REJECTED, MAXDAYS):
    return {
        "Executive Summary": [
            f"""This project delivered a working REST backend for the Classroom and Computer Laboratory Booking System (CCLBS), a university room-reservation application whose repository held a React front end with in-memory demonstration data but no server component at all. The backend was built in Node.js 22 with Express and the platform's built-in SQLite driver, exposing {ENDPOINTS} endpoints for authentication, rooms, bookings, users and reporting, and enforcing reservation rules on the server: operating hours, capacity, slot overlap, room availability and a role-based approval workflow. A {TESTS}-case automated suite runs under Node's built-in test runner; the first execution of an earlier 60-case suite produced 53 passes and 7 failures, every defect was corrected, and the current suite reports {PASSED} passes and {FAILED} failures. The result is a runnable, tested backend rather than a deployed product: authentication is demonstration-grade, nothing is hosted, and the React client is not yet connected.""",
        ],
        "Introduction, Problem, Requirements and Scope": [
            """Scheduling shared teaching space is a genuine commercial problem for any organisation owning scarce, expensive facilities. A computer laboratory represents a large capital investment and a fixed staffing cost, yet where bookings live in email threads, spreadsheets or a paper diary the same room is promised twice, sessions are relocated at short notice, and nobody can answer how full the laboratories are. The stakeholders are students, who need to reserve a laboratory or seminar room reliably; academic staff, who need teaching slots confirmed quickly; administrators and estates staff, who approve requests and need utilisation evidence; and the institution, which needs an auditable record of room usage. The approved objective was the server-side foundation: a persistent data store, a documented HTTP contract, server-enforced booking rules, and an automated suite proving those rules hold.""",
            """Ten functional requirements were derived from the behaviours the existing interface already assumes: sign-in by university identifier returning a role (FR1); a searchable, filterable room catalogue (FR2); an hour-by-hour availability grid (FR3); rejection of conflicting bookings (FR4); an operating-hours limit (FR5); a capacity limit (FR6); student requests routed through approval while staff bookings auto-confirm (FR7); cancellation and rescheduling (FR8); administrative control of rooms and roles (FR9); and reporting of totals, cancellations, peak hours and per-room utilisation (FR10). Five non-functional requirements apply: one consistent machine-readable error envelope, authorisation enforced on the server rather than the client, no external database service, deterministic and isolated automated tests, and validation on every write path. Scope was kept deliberately narrow, with exclusions stated explicitly: production single sign-on, notifications, payment, deployment, accessibility remediation of the front end and client integration are out of scope and are reported as unfinished rather than counted as delivered. Success was defined as every requirement traceable to an endpoint and a test, all such tests passing from a clean clone, and the service starting with no manual setup.""",
        ],
        "Final Solution Design and Architecture": [
            """The solution is a layered service. The HTTP layer (src/app.js and src/routes/*.js) owns parsing, routing and status codes. The authorisation layer (src/middleware/auth.js) resolves the caller from a bearer token and attaches a database-sourced user record. The service layer (src/services/bookingService.js) holds all reservation logic; a validation layer (src/validation.js) supplies reusable field checks; and the persistence layer (src/db.js) owns the schema and seed. The governing design rule is that no reservation rule lives in a route handler: a route validates shape, calls the service and formats the result, which makes the rules testable in isolation and impossible to bypass by calling the API directly instead of the interface.""",
            """Three tables carry the domain model with foreign keys enforcing integrity: users stores identity and role; rooms stores the estate with capacity, type and a JSON-encoded equipment list; bookings stores the reservation referencing one user and one room. Three checkpoint constraints push business rules into the schema itself — bookings requires end_hour > start_hour, both hour columns are range-bound, and status is restricted to the four legal states. A composite index on (room_id, date) supports the availability query, and a partial unique index on (room_id, date, start_hour) restricted to live statuses makes the database refuse two confirmed or pending bookings for the same slot, closing a race that application-level checking cannot fully eliminate.""",
            """The booking flow is: authenticate the token; validate field presence and types; load the room and refuse it if unknown or inactive; check the operating window; compare attendees against capacity; reject past dates and dates beyond the 90-day horizon; run the overlap query; then apply the role rule, writing pending for students and confirmed for staff, and return the booking with a reference code. Failure at any point throws a typed error which one handler converts into the envelope {error:{code,message,details}}, so every rejection names the field and rule that failed. The environment is Node.js 22, Express 4 and node:sqlite: no compiler, container or external service is required. The component and data-flow view appears in Appendix E, Listing E-3.""",
            """The most important design change since the first assessment is the replacement of an in-memory mock array with a relational store. Previously the booking list lived in src/data/mockData.ts and was mutated in a React context object, so rules such as overlap were only implied by the interface and all state vanished on refresh. Those same seven users, eight rooms and ten bookings now live in SQLite, where the rules are explicit and permanent. Two smaller changes were forced by testing: password-style authentication was abandoned because the interface collects no password, and the last-administrator guard was added after a test showed self-demotion could lock the institution out of its own console.""",
        ],
        "Development and Implementation Process": [
            """The work followed a short iterative cycle in four stages. Foundation created the project skeleton, the SQLite schema and the seed translated from the front end's mock module, and delivered authentication with the room and booking listing endpoints. Rules implemented the booking service and its checks. Administration added room CRUD, role management and three reporting endpoints. Hardening was the most valuable stage and is what the evidence in Appendix C reflects: the suite was written, executed, and every failure diagnosed and fixed.""",
            """Three technical decisions shaped the outcome. Persistence uses node:sqlite, the driver built into Node 22, rather than better-sqlite3, removing a native compilation step so the project runs from a clone on a machine with only Node installed, which matters for a marker reproducing the evidence; the trade-off is that the module sits behind an experimental flag, so commands run as node --experimental-sqlite and the driver may change in future releases. Placeholders are used for every value in every statement, including the sign-in lookup, so no input reaches SQL text. Testing uses the built-in runner and fetch rather than Jest or Supertest, keeping the dependency list to one package, Express itself.""",
            f"""The first execution of the original 60-case suite produced 53 passes and 7 failures, which became the recorded defects. D-01: a student's list returned an unexpected count because the ownership filter ran after the row limit; it now runs in SQL before limiting. D-02: another user's booking returned HTTP 200 to a student; the route now raises the same not-found error as for a missing identifier, so the API does not confirm that records exist for callers who may not see them. D-03: a reschedule colliding with an existing booking succeeded because the overlap query did not exclude the booking being moved; the identifier is now passed in. D-04 and D-05: analytics assertions were themselves wrong, assuming eight rooms after the suite created a ninth; expectations now derive from the live catalogue, and a consistency test reconciles the summary endpoint against the list it aggregates. D-06: the last-administrator guard surfaced as HTTP 500 because the route built its error incorrectly; a dedicated conflict helper was added. D-07: the hardening run exposed a fault in a test fixture whose end hour passed the 22:00 close; it was rewritten with in-window hours.""",
            f"""The lessons are concrete rather than general. Testing before trusting the implementation immediately produced seven real defects, five in code and two in the tests; had the suite been written last to demonstrate success, the overlap and authorisation faults would have shipped. Test isolation mattered as much as coverage: several early failures came from fixtures colliding with seed data, which is why the suite now allocates slots from a monotonic counter advancing both date and hour, making tests order-independent. The value of pushing rules into the database was shown by the partial unique index, which closes a race no application check can fully eliminate. Comparing plan with actual delivery: all ten functional requirements were implemented as planned; notifications, single sign-on, deployment and client integration remain out of scope by agreement and are reported as remaining work. The final suite comprises {TESTS} cases reporting {PASSED} passes and {FAILED} failures in about 1.1 seconds.""",
        ],
        "Code, Pseudocode, or Prototype Explanation": [
            """The implementation is eleven JavaScript modules and five test files, listed in full in Appendix A. The core artefact is src/services/bookingService.js, the rule engine. Its central function, validateSlot, returns the room record or throws: it refuses an unknown or inactive room, rejects a slot whose end is not after its start, enforces the 08:00–22:00 window, compares attendees against capacity, rejects past dates and dates beyond 90 days, and runs the overlap query. That query is the algorithmic heart of the system and uses a half-open interval, clashing only where an existing start precedes the candidate end and an existing end follows the candidate start. A booking ending at 11:00 therefore does not conflict with one starting at 11:00 — the behaviour a timetabling system needs and which a naive equality test gets wrong — and the query filters to live statuses, so cancelled and rejected bookings release their slot automatically.""",
            """Creation and state change are deliberately separated. createBooking calls validateSlot and applies the role rule as a single expression: a student's request is written pending, staff requests confirmed, so approval load falls only where the institution wants human review. The insert is wrapped so a unique-index violation — the database-level race guard described earlier — is translated into the same conflict response the application check produces, meaning the caller sees one consistent error whichever layer caught it. transition() implements the approval workflow as an explicit table of allowed states per action: approve and reject are permitted only from pending and only for administrators; cancel is permitted from pending or confirmed and only for the owner or an administrator. Every invalid transition returns a conflict naming the rule rather than silently succeeding, which is what prevents a rejected booking from later being cancelled.""",
            """Two further modules carry requirements that are easy to overlook. src/middleware/auth.js issues a token composed of a base64url user identifier and a truncated SHA-256 message authentication code over that identifier and a server-side secret, compares it in constant time to avoid leaking information through response timing, and re-reads the user record including role from the database on every request, so a role can never be asserted by the client and deactivating an account takes effect immediately. The second is the error envelope in src/app.js: one handler catches every typed error and returns a machine-readable code, message and details, so clients branch on code rather than parsing prose, while an unexpected exception returns 500 without leaking a stack trace. Together they support the flow demonstrated in Appendix B: a student checks availability, submits a request stored as pending, the grid immediately shows that hour taken, an administrator approves it, and the booking appears confirmed in the student's own list.""",
        ],
        "Testing, Results and Solution Evaluation": [
            f"""The strategy has three layers and runs under one command, npm test. Eight unit cases cover the validation helpers and thirteen more exercise the rule engine directly against an in-memory database, where the boundary conditions live: hours outside the window, zero-length and reversed slots, attendance above capacity, past and out-of-horizon dates, back-to-back slots that must be accepted, and invalid state transitions. The remaining cases are HTTP integration tests that boot the real application on an ephemeral port and drive it with real requests, covering authentication and token rejection, the full booking lifecycle, room filtering and administrator CRUD, role-based access to analytics, and one end-to-end journey through availability, request, approval and visibility. Coverage is requirement-led rather than line-led: every functional requirement has at least one test, and the negative path is tested at least as thoroughly as the happy path. The register and traceability matrix are in Appendix C.""",
            f"""The execution history is the most defensible evidence here. The first run of the original 60-case suite produced 53 passes and 7 failures; after the seven corrections the suite was extended to {TESTS} cases and executed again, reporting {PASSED} passed and {FAILED} failed in about 1.1 seconds. That TAP output is reproduced in Appendix C and rendered as Figure 5, so the counts can be checked against raw console text rather than taken on trust. Two of the seven defects were faults in the tests themselves — a hard-coded room count and a fixture whose end hour passed the closing time — both corrected so expectations derive from live state, which is visible in the current suite's reconciliation of the summary endpoint against the list it aggregates.""",
            f"""Evaluation against the objectives is positive but bounded. The service demonstrably does what was asked: it starts with one command and no external service, persists state across restarts, implements all ten functional requirements, and enforces its rules in the server and in schema constraints rather than in the interface. The evidence capture comprises {EXCHANGES} real HTTP exchanges, of which {REJECTED} exercise rejection paths and return the documented envelope; Figures 1 to 4 show those responses exactly as returned. Performance was adequate at the assessed scale and was not a target: the slowest captured response was a single-digit millisecond figure against an in-memory database, no load testing was performed and no throughput claim is made. Usability was not evaluated with real users and no user acceptance testing took place, which is a genuine gap. The honest summary is a well-tested, runnable backend prototype whose rules are proven by automated tests, not a deployed product.""",
        ],
        "Project Management and Contribution Evaluation": [
            """This was delivered as individual technical work on top of an existing two-person group repository, and the project-management evidence is correspondingly thin. There is no issue tracker, sprint log or meeting record: the repository contains exactly two commits, made on 31 August 2026 — "Front-end setup" by Daljeet and "All the pages for the app" by Parveendeep — which constitute the front end this backend was written against. Appendix D reproduces that history verbatim as the available evidence and states plainly that no task-tracking export, signed contribution table or dated decision log exists. Any contribution table submitted must be completed by the students themselves; it cannot honestly be reconstructed from the artefacts available.""",
            """Self-management is evidenced by the artefacts. The backlog was prioritised by dependency rather than feature appeal: schema and seed first, because every later test needed a deterministic database; authentication next, because protected endpoints depended on it; rules before administration; reporting last, because it aggregates data the earlier stages create. Time was controlled by keeping the toolchain minimal — one runtime dependency and a built-in test runner — so no stage was lost to environment problems, which is why every command here is a one-liner. The principal decision, and the one revised during the work, was to keep the feature set narrow and invest the remaining effort in the test suite; the seven defects that exposed justify it. The principal unsolved problem was test isolation, which consumed more time than any single feature and was resolved by introducing a monotonic slot allocator.""",
        ],
        "Security, Privacy, Ethics, Deployment Readiness and Limitations": [
            """Authorisation is enforced server-side from a database lookup on every request, so a role can never be asserted by the client, and guards sit on routes rather than inside the interface. Every statement is parameterised and every write path validated, so SQL injection is prevented structurally rather than by escaping. Baseline hardening headers, including a content-security policy, frame denial and sniffing protection, are set on every response, and the service hides its identifying header. The limitations are equally concrete: the tokens are self-signed with no expiry, no revocation list and no refresh mechanism; the signing secret comes from an environment variable with a development default; there is no rate limiting, so the sign-in endpoint can be brute-forced; and there is no transport security locally, so the service must sit behind a TLS-terminating proxy before real use. Password authentication was not implemented because the source interface collects no password.""",
            """The schema stores only identity data the institution already holds — name, institutional email, department and role — and no special-category data. Reservations are personal data, so access is scoped: a student's list is filtered in SQL and reading another person's booking returns not-found rather than forbidden, so the API does not confirm that a record exists. No analytics, tracking or outbound network calls are present. Ethically, a system allocating shared public resources should be transparent and reviewable, which is why every rejection names the rule that failed and why approval decisions are status changes on a persistent record rather than deletions. Accessibility was not assessed: the client is out of scope here and no contrast, keyboard or screen-reader audit was performed. Deployment readiness is partial — the service runs anywhere Node 22 exists and creates its own schema at first boot, but needs the experimental driver pinned or replaced, token expiry and revocation, rate limiting, a TLS proxy and reconnection of the React client before an end user benefits.""",
        ],
        "Conclusion and Future Recommendations": [
            f"""The project delivered what was scoped: a runnable REST backend for CCLBS, comprising {ENDPOINTS} endpoints over a persistent SQLite schema with server-enforced reservation rules, role-based authorisation and three analytics reports, supported by a {TESTS}-case suite now reporting {PASSED} passes and {FAILED} failures with its raw output attached as evidence. Its value lies less in the endpoint count than in the rules that are now explicit — operating hours, capacity, overlap and approval enforced in one place, tested directly, and backed by a database constraint closing the race an application-level check cannot. A less expected benefit was the seven defects the suite surfaced before delivery, two of them faults in the tests, evidence that the testing effort produced real quality rather than reassurance.""",
            """What remains incomplete is stated plainly: no deployment, no production authentication, no notifications, no client integration and no user testing. The priority order for continuing is therefore clear. First, rewire the React client to call the API, because until then the system cannot be assessed as a product by a real user. Second, harden the session layer with expiring tokens, revocation and rate limiting. Third, add deployment scaffolding — container, hosted database, TLS proxy and automated backup — after which the experimental driver should be replaced or pinned. Fourth, extend reporting with termly comparisons and export, and add notification on approval, the feature most likely to reduce administrator load in practice. Later, recurring bookings and institutional timetable integration would remove most remaining manual work, and each step should carry the same requirement-led test discipline that made the present limitations visible.""",
        ],
    }
